# SPDX-FileCopyrightText: 2025 The superseedr Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun-data:/gluetun
      - forwarded-port:/tmp/gluetun
    env_file:
      - .gluetun.env
    environment:
      - FIREWALL_VPN_INPUT_PORTS=${CLIENT_PORT}
    restart: unless-stopped

  superseedr:
    build:
      context: .
      args:
        - PRIVATE_BUILD=${PRIVATE_BUILD:-false}
    image: ${IMAGE_NAME:-jagatranvo/superseedr:latest}
    tty: true
    stdin_open: true
    init: true
    entrypoint: ["superseedr"]
    command: []
    network_mode: "service:gluetun"
    depends_on: [gluetun]
    volumes:
      - ${HOST_SUPERSEEDR_ROOT_PATH:-superseedr-root}:/seedbox
      - ${HOST_SUPERSEEDR_SHARE_PATH:-superseedr-share}:/root/.local/share/jagalite.superseedr
      - ${HOST_WINDOWS_WATCH_PATH:-superseedr-windows-watch}:/windows-watch
      - forwarded-port:/port-data
    environment:
      - SUPERSEEDR_DEFAULT_DOWNLOAD_FOLDER=/seedbox
      - SUPERSEEDR_CLIENT_PORT=${CLIENT_PORT:-6881}
      - SUPERSEEDR_SHARED_CONFIG_DIR=${SUPERSEEDR_SHARED_CONFIG_DIR:-}
      - SUPERSEEDR_HOST_ID=${SUPERSEEDR_HOST_ID:-}
      - SUPERSEEDR_WATCH_PATH_1=${SUPERSEEDR_WATCH_PATH_1:-/windows-watch}
    stop_grace_period: 0s

volumes:
  superseedr-root:
  superseedr-share:
  superseedr-windows-watch:
  gluetun-data:
  forwarded-port:

